### ISSUE TITLE
paper missing references

### ISSUE THREAD

**Issue by rgiordan** [paulgovan/BayesianNetwork#8]
"References: Do all archival references that should have a DOI list one (e.g., papers, datasets, software)?"

The paper as-is (in md and pdf form) is entirely missing a references section (even though I see you have populated the bib file).

**Comment by paulgovan** [comment]
Hmm I'm not terribly familiar with markdown, but I think I see the problem. Should be fixed shortly.

**Comment by katyhuff** [comment]
Hi @paulgovan . This still isn't working. Have you tried actually building the paper? (use pandoc). Your paper doesn't seem to actually cite any of the references in your .bib file. Thus, none appear in the list of references. You need to cite references thus `Previous authors [@scutari2009learning] ...`.

Relatedly, it is only possible to do this citation if your bib file has keys for each of the entries (e.g. scutari2009learning) many are missing a key, which should be after the curly brace and before the comma... .

**Comment by paulgovan** [comment]
Ah ok I see. Ok I will actually cite each reference in the paper and add keys to all of them in the .bib file.

**Comment by paulgovan** [comment]
I found that there are at least 2 ways to ensure a reference is included in the References section: an in text citation or use of the `nocite` metadata field. The references appear to be rendering now. Please see commit [https://github.com/paulgovan/BayesianNetwork/commit/6b140c00ea059ed2fa641627be809d855295e217](https://github.com/paulgovan/BayesianNetwork/commit/6b140c00ea059ed2fa641627be809d855295e217).
